# Generated by Django 6.0.3 on 2026-03-20 11:28

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(default=apps.accounts.models.generate_api_token, max_length=128, unique=True),
        ),
    ]
