FDT_CODE = "fdt"
FDT_NAME = "FDT - Five Digits Test"
FDT_CATEGORY = "Funcoes executivas"
FDT_VERSION = "1.0"

FDT_STAGE_LABELS = {
    "leitura": "Leitura",
    "contagem": "Contagem",
    "escolha": "Escolha",
    "alternancia": "Alternancia",
    "inibicao": "Inibicao",
    "flexibilidade": "Flexibilidade",
}

FDT_PROCESS_GROUPS = {
    "leitura": "Processos Automaticos",
    "contagem": "Processos Automaticos",
    "escolha": "Processos Controlados",
    "alternancia": "Processos Controlados",
    "inibicao": "Processos Controlados",
    "flexibilidade": "Processos Controlados",
}

FDT_NORMS = [
    {
        "faixa": "6-8",
        "titulo": "Dados normativos para criancas de 6 a 8 anos",
        "n": 44,
        "idade_min": 6,
        "idade_max": 8,
        "tempos": {
            "leitura": {
                "media": 35.4,
                "dp": 9.3,
                "pc95": 25,
                "pc75": 29,
                "pc50": 34,
                "pc25": 39,
                "pc5": 48,
            },
            "contagem": {
                "media": 51.0,
                "dp": 18.7,
                "pc95": 32,
                "pc75": 40,
                "pc50": 48,
                "pc25": 56,
                "pc5": 83,
            },
            "escolha": {
                "media": 79.4,
                "dp": 24.1,
                "pc95": 41,
                "pc75": 66,
                "pc50": 79,
                "pc25": 94,
                "pc5": 109,
            },
            "alternancia": {
                "media": 93.7,
                "dp": 26.3,
                "pc95": 58,
                "pc75": 75,
                "pc50": 91,
                "pc25": 113,
                "pc5": 133,
            },
            "inibicao": {
                "media": 44.0,
                "dp": 19.5,
                "pc95": 17,
                "pc75": 31,
                "pc50": 43,
                "pc25": 55,
                "pc5": 76,
            },
            "flexibilidade": {
                "media": 58.3,
                "dp": 20.8,
                "pc95": 26,
                "pc75": 41,
                "pc50": 55,
                "pc25": 75,
                "pc5": 92,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.5,
                "dp": 1.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 4,
            },
            "escolha": {
                "media": 2.6,
                "dp": 2.6,
                "pc95": 0,
                "pc75": 0,
                "pc50": 2,
                "pc25": 4,
                "pc5": 9,
            },
            "alternancia": {
                "media": 3.9,
                "dp": 4.7,
                "pc95": 0,
                "pc75": 1,
                "pc50": 2,
                "pc25": 5,
                "pc5": 10,
            },
        },
    },
    {
        "faixa": "9-10",
        "titulo": "Dados normativos para criancas de 9 a 10 anos",
        "n": 129,
        "idade_min": 9,
        "idade_max": 10,
        "tempos": {
            "leitura": {
                "media": 29.4,
                "dp": 5.2,
                "pc95": 22,
                "pc75": 26,
                "pc50": 29,
                "pc25": 32,
                "pc5": 38,
            },
            "contagem": {
                "media": 39.4,
                "dp": 7.1,
                "pc95": 28,
                "pc75": 34,
                "pc50": 39,
                "pc25": 43,
                "pc5": 52,
            },
            "escolha": {
                "media": 65.1,
                "dp": 13.5,
                "pc95": 46,
                "pc75": 56,
                "pc50": 63,
                "pc25": 73,
                "pc5": 88,
            },
            "alternancia": {
                "media": 78.5,
                "dp": 23.2,
                "pc95": 54,
                "pc75": 67,
                "pc50": 75,
                "pc25": 87,
                "pc5": 101,
            },
            "inibicao": {
                "media": 35.7,
                "dp": 11.7,
                "pc95": 19,
                "pc75": 28,
                "pc50": 35,
                "pc25": 42,
                "pc5": 57,
            },
            "flexibilidade": {
                "media": 49.1,
                "dp": 21.8,
                "pc95": 28,
                "pc75": 39,
                "pc50": 46,
                "pc25": 57,
                "pc5": 73,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.4,
                "dp": 0.8,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 2,
            },
            "escolha": {
                "media": 1.9,
                "dp": 1.9,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 3,
                "pc5": 6,
            },
            "alternancia": {
                "media": 3.1,
                "dp": 2.9,
                "pc95": 0,
                "pc75": 1,
                "pc50": 2,
                "pc25": 4,
                "pc5": 8,
            },
        },
    },
    {
        "faixa": "11-12",
        "titulo": "Dados normativos para criancas de 11 a 12 anos",
        "n": 59,
        "idade_min": 11,
        "idade_max": 12,
        "tempos": {
            "leitura": {
                "media": 29.4,
                "dp": 13.5,
                "pc95": 20,
                "pc75": 24,
                "pc50": 27,
                "pc25": 32,
                "pc5": 47,
            },
            "contagem": {
                "media": 38.2,
                "dp": 11.4,
                "pc95": 25,
                "pc75": 32,
                "pc50": 36,
                "pc25": 44,
                "pc5": 54,
            },
            "escolha": {
                "media": 59.4,
                "dp": 28.9,
                "pc95": 38,
                "pc75": 48,
                "pc50": 56,
                "pc25": 62,
                "pc5": 93,
            },
            "alternancia": {
                "media": 68.6,
                "dp": 27.5,
                "pc95": 46,
                "pc75": 55,
                "pc50": 66,
                "pc25": 73,
                "pc5": 96,
            },
            "inibicao": {
                "media": 30.0,
                "dp": 18.0,
                "pc95": 12,
                "pc75": 20,
                "pc50": 28,
                "pc25": 35,
                "pc5": 51,
            },
            "flexibilidade": {
                "media": 39.2,
                "dp": 17.7,
                "pc95": 16,
                "pc75": 30,
                "pc50": 39,
                "pc25": 44,
                "pc5": 68,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.1,
                "dp": 0.3,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 1,
            },
            "contagem": {
                "media": 0.4,
                "dp": 1.1,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 3,
            },
            "escolha": {
                "media": 1.7,
                "dp": 2.7,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 2,
                "pc5": 10,
            },
            "alternancia": {
                "media": 2.6,
                "dp": 3.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 2,
                "pc25": 3,
                "pc5": 10,
            },
        },
    },
    {
        "faixa": "13-15",
        "titulo": "Dados normativos para adolescentes de 13 a 15 anos",
        "n": 46,
        "idade_min": 13,
        "idade_max": 15,
        "tempos": {
            "leitura": {
                "media": 23.3,
                "dp": 5.2,
                "pc95": 17,
                "pc75": 20,
                "pc50": 23,
                "pc25": 26,
                "pc5": 34,
            },
            "contagem": {
                "media": 30.0,
                "dp": 7.3,
                "pc95": 21,
                "pc75": 24,
                "pc50": 28,
                "pc25": 35,
                "pc5": 44,
            },
            "escolha": {
                "media": 47.1,
                "dp": 11.8,
                "pc95": 33,
                "pc75": 40,
                "pc50": 45,
                "pc25": 53,
                "pc5": 68,
            },
            "alternancia": {
                "media": 56.9,
                "dp": 15.2,
                "pc95": 36,
                "pc75": 46,
                "pc50": 53,
                "pc25": 67,
                "pc5": 81,
            },
            "inibicao": {
                "media": 23.8,
                "dp": 9.0,
                "pc95": 8,
                "pc75": 19,
                "pc50": 23.5,
                "pc25": 29,
                "pc5": 42,
            },
            "flexibilidade": {
                "media": 33.6,
                "dp": 12.5,
                "pc95": 14,
                "pc75": 25,
                "pc50": 32,
                "pc25": 43,
                "pc5": 53,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.0,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.2,
                "dp": 0.5,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 2,
            },
            "escolha": {
                "media": 1.6,
                "dp": 2.4,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 2,
                "pc5": 7,
            },
            "alternancia": {
                "media": 1.9,
                "dp": 2.1,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 3,
                "pc5": 5,
            },
        },
    },
    {
        "faixa": "16-18",
        "titulo": "Dados normativos para adolescentes de 16 a 18 anos",
        "n": 44,
        "idade_min": 16,
        "idade_max": 18,
        "tempos": {
            "leitura": {
                "media": 20.4,
                "dp": 4.1,
                "pc95": 16,
                "pc75": 17,
                "pc50": 20,
                "pc25": 23,
                "pc5": 29,
            },
            "contagem": {
                "media": 23.8,
                "dp": 3.5,
                "pc95": 19,
                "pc75": 21,
                "pc50": 24,
                "pc25": 26,
                "pc5": 30,
            },
            "escolha": {
                "media": 34.0,
                "dp": 5.9,
                "pc95": 25,
                "pc75": 29,
                "pc50": 33,
                "pc25": 39,
                "pc5": 44,
            },
            "alternancia": {
                "media": 44.8,
                "dp": 9.1,
                "pc95": 34,
                "pc75": 38,
                "pc50": 42,
                "pc25": 51,
                "pc5": 63,
            },
            "inibicao": {
                "media": 13.6,
                "dp": 4.9,
                "pc95": 6,
                "pc75": 10.5,
                "pc50": 13,
                "pc25": 16.5,
                "pc5": 22,
            },
            "flexibilidade": {
                "media": 24.4,
                "dp": 7.8,
                "pc95": 16,
                "pc75": 19,
                "pc50": 22,
                "pc25": 27,
                "pc5": 44,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.0,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.0,
                "dp": 0.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "escolha": {
                "media": 0.6,
                "dp": 1.8,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 3,
            },
            "alternancia": {
                "media": 1.5,
                "dp": 1.7,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 2,
                "pc5": 4,
            },
        },
    },
    {
        "faixa": "19-34",
        "titulo": "Dados normativos para adultos de 19 a 34 anos",
        "n": 349,
        "idade_min": 19,
        "idade_max": 34,
        "tempos": {
            "leitura": {
                "media": 22.0,
                "dp": 5.6,
                "pc95": 16,
                "pc75": 19,
                "pc50": 21,
                "pc25": 25,
                "pc5": 31,
            },
            "contagem": {
                "media": 24.8,
                "dp": 5.2,
                "pc95": 19,
                "pc75": 22,
                "pc50": 24,
                "pc25": 27,
                "pc5": 34,
            },
            "escolha": {
                "media": 36.9,
                "dp": 10.0,
                "pc95": 27,
                "pc75": 31,
                "pc50": 35,
                "pc25": 40,
                "pc5": 52,
            },
            "alternancia": {
                "media": 46.0,
                "dp": 13.0,
                "pc95": 33,
                "pc75": 38,
                "pc50": 44,
                "pc25": 50,
                "pc5": 64,
            },
            "inibicao": {
                "media": 14.8,
                "dp": 8.3,
                "pc95": 5,
                "pc75": 11,
                "pc50": 14,
                "pc25": 18,
                "pc5": 28,
            },
            "flexibilidade": {
                "media": 23.9,
                "dp": 10.8,
                "pc95": 10,
                "pc75": 17,
                "pc50": 22,
                "pc25": 29,
                "pc5": 42,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.1,
                "dp": 0.4,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 1,
            },
            "escolha": {
                "media": 0.4,
                "dp": 0.9,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 1,
                "pc5": 2,
            },
            "alternancia": {
                "media": 0.9,
                "dp": 1.5,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 1,
                "pc5": 3,
            },
        },
    },
    {
        "faixa": "35-59",
        "titulo": "Dados normativos para adultos de 35 a 59 anos",
        "n": 261,
        "idade_min": 35,
        "idade_max": 59,
        "tempos": {
            "leitura": {
                "media": 23.9,
                "dp": 6.5,
                "pc95": 17,
                "pc75": 20,
                "pc50": 23,
                "pc25": 26,
                "pc5": 37,
            },
            "contagem": {
                "media": 27.1,
                "dp": 7.2,
                "pc95": 19,
                "pc75": 22,
                "pc50": 26,
                "pc25": 30,
                "pc5": 40,
            },
            "escolha": {
                "media": 41.7,
                "dp": 14.5,
                "pc95": 28,
                "pc75": 32,
                "pc50": 39,
                "pc25": 46,
                "pc5": 65,
            },
            "alternancia": {
                "media": 53.6,
                "dp": 18.4,
                "pc95": 34,
                "pc75": 43,
                "pc50": 48,
                "pc25": 60,
                "pc5": 89,
            },
            "inibicao": {
                "media": 17.8,
                "dp": 12.0,
                "pc95": 5,
                "pc75": 11,
                "pc50": 15,
                "pc25": 21,
                "pc5": 38,
            },
            "flexibilidade": {
                "media": 29.7,
                "dp": 15.7,
                "pc95": 14,
                "pc75": 20,
                "pc50": 26,
                "pc25": 34,
                "pc5": 55,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.0,
                "dp": 0.2,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "escolha": {
                "media": 0.7,
                "dp": 1.9,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 1,
                "pc5": 3,
            },
            "alternancia": {
                "media": 1.5,
                "dp": 2.6,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 2,
                "pc5": 6,
            },
        },
    },
    {
        "faixa": "60-75",
        "titulo": "Dados normativos para idosos de 60 a 75 anos",
        "n": 146,
        "idade_min": 60,
        "idade_max": 75,
        "tempos": {
            "leitura": {
                "media": 26.6,
                "dp": 6.2,
                "pc95": 18,
                "pc75": 22,
                "pc50": 25,
                "pc25": 30,
                "pc5": 37,
            },
            "contagem": {
                "media": 29.7,
                "dp": 6.3,
                "pc95": 21,
                "pc75": 25,
                "pc50": 28,
                "pc25": 33,
                "pc5": 41,
            },
            "escolha": {
                "media": 47.4,
                "dp": 11.3,
                "pc95": 30,
                "pc75": 39,
                "pc50": 46,
                "pc25": 53,
                "pc5": 68,
            },
            "alternancia": {
                "media": 65.3,
                "dp": 18.0,
                "pc95": 41,
                "pc75": 52,
                "pc50": 62,
                "pc25": 78,
                "pc5": 93,
            },
            "inibicao": {
                "media": 20.8,
                "dp": 9.0,
                "pc95": 9,
                "pc75": 15,
                "pc50": 19.5,
                "pc25": 26,
                "pc5": 39,
            },
            "flexibilidade": {
                "media": 38.7,
                "dp": 15.7,
                "pc95": 18,
                "pc75": 28,
                "pc50": 35,
                "pc25": 49,
                "pc5": 63,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.0,
                "dp": 0.1,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.1,
                "dp": 0.3,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 1,
            },
            "escolha": {
                "media": 0.8,
                "dp": 1.1,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 1,
                "pc5": 3,
            },
            "alternancia": {
                "media": 1.7,
                "dp": 2.0,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 3,
                "pc5": 6,
            },
        },
    },
    {
        "faixa": "76+",
        "titulo": "Dados normativos para idosos de 76 ou mais anos",
        "n": 55,
        "idade_min": 76,
        "idade_max": 200,
        "tempos": {
            "leitura": {
                "media": 29.2,
                "dp": 5.4,
                "pc95": 20,
                "pc75": 25,
                "pc50": 29,
                "pc25": 34,
                "pc5": 38,
            },
            "contagem": {
                "media": 31.9,
                "dp": 7.8,
                "pc95": 21,
                "pc75": 26,
                "pc50": 31,
                "pc25": 36,
                "pc5": 46,
            },
            "escolha": {
                "media": 53.2,
                "dp": 15.7,
                "pc95": 33,
                "pc75": 44,
                "pc50": 49,
                "pc25": 62,
                "pc5": 96,
            },
            "alternancia": {
                "media": 75.4,
                "dp": 20.3,
                "pc95": 48,
                "pc75": 61,
                "pc50": 74,
                "pc25": 89,
                "pc5": 108,
            },
            "inibicao": {
                "media": 24.0,
                "dp": 13.4,
                "pc95": 7,
                "pc75": 16,
                "pc50": 21,
                "pc25": 29,
                "pc5": 63,
            },
            "flexibilidade": {
                "media": 46.02,
                "dp": 17.6,
                "pc95": 22,
                "pc75": 35,
                "pc50": 43,
                "pc25": 56,
                "pc5": 71,
            },
        },
        "erros": {
            "leitura": {
                "media": 0.1,
                "dp": 0.6,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "contagem": {
                "media": 0.0,
                "dp": 0.3,
                "pc95": 0,
                "pc75": 0,
                "pc50": 0,
                "pc25": 0,
                "pc5": 0,
            },
            "escolha": {
                "media": 1.7,
                "dp": 2.4,
                "pc95": 0,
                "pc75": 0,
                "pc50": 1,
                "pc25": 3,
                "pc5": 8,
            },
            "alternancia": {
                "media": 3.5,
                "dp": 4.3,
                "pc95": 0,
                "pc75": 1,
                "pc50": 2,
                "pc25": 5,
                "pc5": 14,
            },
        },
    },
]
