# Generated by Django 6.0.3 on 2026-03-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título do caso')),
                ('referral_reason', models.TextField(blank=True, verbose_name='motivo do encaminhamento')),
                ('evaluation_purpose', models.TextField(blank=True, verbose_name='finalidade da avaliação')),
                ('clinical_hypothesis', models.TextField(blank=True, verbose_name='hipótese clínica')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('collecting_data', 'Coletando dados'), ('tests_in_progress', 'Testes em andamento'), ('scoring', 'Pontuando testes'), ('writing_report', 'Laudo em redação'), ('in_review', 'Em revisão'), ('approved', 'Aprovado'), ('archived', 'Arquivado')], default='draft', max_length=30, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='prioridade')),
                ('is_archived', models.BooleanField(default=False, verbose_name='arquivado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('general_notes', models.TextField(blank=True, verbose_name='observações gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por')),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='profissional responsável')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
    ]
