# Generated by Django 6.0.3 on 2026-03-21 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_reason', models.TextField(blank=True, verbose_name='motivo do encaminhamento')),
                ('evaluation_purpose', models.TextField(blank=True, verbose_name='finalidade da avaliação')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('collecting_data', 'Coletando dados'), ('scoring', 'Pontuando testes'), ('writing', 'Redigindo laudo'), ('in_review', 'Em revisão'), ('approved', 'Aprovado'), ('archived', 'Arquivado')], default='draft', max_length=30, verbose_name='status')),
                ('general_notes', models.TextField(blank=True, verbose_name='observações gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='profissional responsável')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
    ]
