# Generated by Django 6.0.3 on 2026-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sex', models.CharField(blank=True, max_length=20, verbose_name='sexo')),
                ('schooling', models.CharField(blank=True, max_length=120, verbose_name='escolaridade')),
                ('school_name', models.CharField(blank=True, max_length=255, verbose_name='escola')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='ocupação')),
                ('mother_name', models.CharField(blank=True, max_length=255, verbose_name='nome da mãe')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='nome do pai')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=80, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['full_name'],
            },
        ),
    ]
