# Generated by Django 6.0.3 on 2026-03-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='grade_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='série/ano'),
        ),
        migrations.AddField(
            model_name='patient',
            name='institution',
            field=models.CharField(blank=True, max_length=255, verbose_name='instituição'),
        ),
    ]
