# Generated by Django 6.0.3 on 2026-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_schooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='schooling',
            field=models.CharField(blank=True, choices=[('preschool', 'Ensino Pré-escolar'), ('elementary', 'Ensino Fundamental'), ('middle', 'Ensino Médio'), ('higher', 'Ensino Superior'), ('higher_incomplete', 'Ensino Superior Incompleto')], max_length=120, verbose_name='escolaridade'),
        ),
    ]
