# Generated by Django 6.0.3 on 2026-03-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_schooling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='institution',
        ),
    ]
