# Generated by Django 6.0.3 on 2026-03-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='occupation',
        ),
    ]
