# Generated by Django 6.0.3 on 2026-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patient_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nome do responsável'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone do responsável'),
        ),
    ]
