# Generated by Django 6.0.3 on 2026-03-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_responsible_name_patient_responsible_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='observações'),
        ),
    ]
