# Generated by Django 6.0.3 on 2026-03-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_notes_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do responsável'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='telefone do responsável'),
        ),
    ]
