# Generated by Django 6.0.3 on 2026-03-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categoria')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='versão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(blank=True, null=True, verbose_name='data de aplicação')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='dados brutos')),
                ('computed_payload', models.JSONField(blank=True, default=dict, verbose_name='dados calculados')),
                ('classified_payload', models.JSONField(blank=True, default=dict, verbose_name='dados classificados')),
                ('reviewed_payload', models.JSONField(blank=True, default=dict, verbose_name='dados revisados')),
                ('interpretation_text', models.TextField(blank=True, verbose_name='interpretação')),
                ('is_validated', models.BooleanField(default=False, verbose_name='validado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_applications', to='evaluations.evaluation', verbose_name='avaliação')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tests.instrument', verbose_name='instrumento')),
            ],
            options={
                'verbose_name': 'Aplicação de teste',
                'verbose_name_plural': 'Aplicações de teste',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestInterpretationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_templates', to='tests.instrument', verbose_name='instrumento')),
            ],
            options={
                'verbose_name': 'Template de interpretação',
                'verbose_name_plural': 'Templates de interpretação',
                'ordering': ['instrument__name', 'title'],
            },
        ),
    ]
