# Generated by Django 5.2.12 on 2026-04-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationprogressentry'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsection',
            options={'ordering': ['order'], 'verbose_name': 'Seção de laudo', 'verbose_name_plural': 'Seções de laudo'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='interested_party',
        ),
        migrations.RemoveField(
            model_name='report',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='report',
            name='snapshot_payload',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='edited_text',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='generated_text',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='source_payload',
        ),
        migrations.AddField(
            model_name='report',
            name='context_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='contexto clínico'),
        ),
        migrations.AddField(
            model_name='report',
            name='edited_text',
            field=models.TextField(blank=True, verbose_name='texto editado'),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='gerado em'),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_text',
            field=models.TextField(blank=True, verbose_name='texto gerado pela IA'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='content_edited',
            field=models.TextField(blank=True, verbose_name='conteúdo editado'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='content_generated',
            field=models.TextField(blank=True, verbose_name='conteúdo IA'),
        ),
        migrations.AlterField(
            model_name='report',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='evaluations.evaluation', verbose_name='avaliação'),
        ),
        migrations.AlterField(
            model_name='report',
            name='final_text',
            field=models.TextField(blank=True, verbose_name='texto finalizado'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('generating', 'Gerando texto...'), ('in_review', 'Em revisão'), ('finalized', 'Finalizado'), ('sent', 'Enviado ao paciente')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='Laudo Neuropsicológico', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='bloqueado para edição'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='key',
            field=models.CharField(max_length=100, verbose_name='chave da seção'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título da seção'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='versão')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.report', verbose_name='laudo')),
            ],
            options={
                'verbose_name': 'Versão de laudo',
                'verbose_name_plural': 'Versões de laudo',
                'ordering': ['-version_number'],
            },
        ),
    ]
