# Generated by Django 5.2.12 on 2026-04-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='interested_party',
            field=models.CharField(blank=True, max_length=255, verbose_name='interessado'),
        ),
        migrations.AddField(
            model_name='report',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='finalidade'),
        ),
    ]
