# Generated by Django 5.2.12 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_report_interested_party_report_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="ai_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="metadados de IA"
            ),
        ),
        migrations.AddField(
            model_name="reportsection",
            name="generation_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="metadados da geracao"
            ),
        ),
        migrations.AddField(
            model_name="reportsection",
            name="warnings_payload",
            field=models.JSONField(
                blank=True, default=list, verbose_name="avisos da geracao"
            ),
        ),
    ]
