from __future__ import annotations


BFP_CODE = "bfp"
BFP_NAME = "BFP - Bateria Fatorial de Personalidade"

SAMPLE_LABELS = {
    "geral": "Geral",
    "masculino": "Masculino",
    "feminino": "Feminino",
}

RESPONSE_OPTIONS = {
    1: "Discordo Totalmente",
    2: "Discordo",
    3: "Discordo Parcialmente",
    4: "Neutro",
    5: "Concordo Parcialmente",
    6: "Concordo",
    7: "Concordo Totalmente",
}

FACTOR_DEFINITIONS = {
    "NN": {
        "name": "Neuroticismo",
        "facets": ["N1", "N2", "N3", "N4"],
    },
    "EE": {
        "name": "Extroversão",
        "facets": ["E1", "E2", "E3", "E4"],
    },
    "SS": {
        "name": "Socialização",
        "facets": ["S1", "S2", "S3"],
    },
    "RR": {
        "name": "Realização",
        "facets": ["R1", "R2", "R3"],
    },
    "AA": {
        "name": "Abertura",
        "facets": ["A1", "A2", "A3"],
    },
}

FACET_DEFINITIONS = {
    "N1": {
        "name": "Vulnerabilidade",
        "factor": "NN",
        "items": [55, 60, 73, 75, 79, 82, 89, 110, 118],
        "reversed": [],
        "description": "Avalia o quão frágeis as pessoas são emocionalmente. Indica o quanto os indivíduos vivenciam sofrimento emocional em decorrência da sua percepção de como os outros os aceitam. Relaciona-se também com dependência emocional e dificuldade para tomada de decisões em função do medo de decepcionar as pessoas.",
        "low_text": "Tende a ser independente emocionalmente em relação aos outros, o que lhe proporciona facilidade para tomar decisões. Em função dessa característica tende a ser pouco preocupado(a) com opiniões alheias e usualmente toma decisões e enfrenta problemas sem levar em consideração os demais, o que pode afetar a qualidade de suas relações interpessoais. Tende a ter identidade bem definida, menor probabilidade de apresentar Ansiedade ou Depressão. Pode também vivenciar emoções positivas mais intensamente e apresentar autoimagem distorcida positivamente. Pode ainda mostrar-se soberbo e auto suficiente.",
        "high_text": "Tende a apresentar identidade difusa (falta de clareza sobre si mesmo), baixa autoestima. Tais distorções pode levá-lo(a) a ter medo de que pessoas importantes para si o(a) deixe em decorrência de seus erros. Usualmente, pode ser capaz de ter atitudes que vão contra sua vontade, com o objetivo de agradar aos outros. Pode mostrar-se inseguro(a), dependente das pessoas próximas e ter dificuldades em tomar decisões, mesmo em situações triviais do dia a dia. Apresenta maior probabilidade de desevolver Ansiedade ou Depressão. Tende ainda a apresentar autoimagem distorcida negativamente, o que pode levá-lo(a) a vivenciar emoções negativas mais intensamente.",
    },
    "N2": {
        "name": "Instabilidade Emocional",
        "factor": "NN",
        "items": [25, 51, 65, 77, 86, 102],
        "reversed": [],
        "description": "Avalia o quanto as pessoas descrevem-se como irritáveis, nervosas, e com grandes variações de humor.",
        "low_text": "Tende apresentar menor variações de humor e geralmente não toma decisões de forma impulsiva. Tende a apresentar ações mais controladas ao sentir desconforto emocional. Pode também mostrar-se cauteloso(a), cuidadoso(a), ponderado(a), sensato(a), prudente em suas decisões. Tende ainda apresentar satisfatória habilidade em lidar com sentimentos negativistas, alta tolerância às frustrações e a fazer avaliação mais positiva da vida.",
        "high_text": "Tende a agir impulsivamente quando sente algum desconforto emocional, tomando decisões precipitadas com relativa frequência. Pode ainda apresentar grandes oscilações de humor sem um motivo aparente e pode ter dificuldade para controlar seus sentimentos negativos, além de apresentar baixa tolerância à frustração e a fazer avaliação mais negativa da vida.",
    },
    "N3": {
        "name": "Passividade/Falta de Energia",
        "factor": "NN",
        "items": [13, 22, 35, 37, 95, 100],
        "reversed": [],
        "description": "Avalia o nível de atividade das pessoas e seu empenho para resolver situações rapidamente. Tal faceta também se relaciona à velocidade de decisão.",
        "low_text": "Tende a ser pró-ativa, a iniciar e concluir tarefas importantes e usualmente toma decisões agilmente. Pode apresentar forte motivação intrínseca para realizar seus planos sem precisar de estímulos ou auxílio externo para iniciar e levá-lo(a) adiante e concluir projetos.",
        "high_text": "Tende a apresentar um comportamento de procrastinação, tendo grande dificuldade para iniciar tarefas, mesmo que simples. Pode também apresentar dificuldade para manter a motivação em afazeres longos ou difíceis, tendendo a abandoná-los antes de sua conclusão. Pode ainda necessitar de estímulo externo para conseguir levar adiante seus planos e, com frequência, pode abster-se de tomar decisões mesmo sobre assuntos de seu interesse.",
    },
    "N4": {
        "name": "Depressão",
        "factor": "NN",
        "items": [16, 29, 40, 48, 70, 106, 121, 124],
        "reversed": [16],
        "description": "Avalia os padrões de interpretações que os indivíduos apresentam em relação aos eventos que ocorrem ao longo de suas vidas, mais especificamente a percepção que possuem sobre as expectativas de futuro e sua capacidade para lidar com dificuldades que possam ocorrer em suas vidas.",
        "low_text": "Tende a ter uma expectativa muito positiva em relação ao seu futuro, mostrando-se espereançoso(a). Pode ter dificuldade para reconhecer eventos negativos e avaliar os problemas, minimizando-os. Pode mostrar-se satisfeitos com sua vida e apresentar satisfatórios sentimentos de pertencimento. Tende a ter clareza de objetivos para a vida. Tende ainda a acreditar em sua capacidade para lidar com as eventuais dificuldades que podem ocorrer. Em níveis extremos, tal característica pode indicar uma dificuldade para perceber quando está diante de problemas reais, e isso pode prejudicá-lo(a), em decorrência de uma falta de atitudes que poderiam resolver efetivamente os problemas que precisam ser enfrentados.",
        "high_text": "Pode ter dificuldade para reconhecer eventos positivos, maximizando-os. Tende a relatar expectativas negativas em relação ao seu futuro, o que caracteriza desesperança. Pode relatar ter uma vida monótona e sem emoção. Tende a sentir-se solitário(a), sem objetivos claros para vida. Pode ainda considerar-se incapaz de lidar com as dificuldades do cotidiano.",
    },
    "E1": {
        "name": "Comunicação",
        "factor": "EE",
        "items": [17, 38, 66, 97, 105, 120],
        "reversed": [17, 38, 66],
        "description": "Descreve o quão comunicativas e expansivas as pessoas acreditam que são.",
        "low_text": "Pode preferir não se expressar em público. Tende a apresentar dificuldades em tomar a iniciativa para conhcer novas pessoas e a preferir um maior distanciamento nas relações interpessoais. Pode também mostrar-se constrangido(a) em situações de maior exposição e preferir falar pouco sobre si mesmo(a).",
        "high_text": "Usualmente pode apresentar facilidade para falar em público, para conhecer novas pessoas e, tendem a apresentar um maior senso de intimidade, rapidamente avaliando como profundas relações relativamente recentes. Além disso, tende a iniciar conversas com os outros, expressar suas opiniões e interesses quando estão em grupo e indicam que dificilmente sentem-se constrangidas em situações sociais.",
    },
    "E2": {
        "name": "Altivez",
        "factor": "EE",
        "items": [3, 5, 14, 78, 93, 99, 111],
        "reversed": [],
        "description": "Descreve a percepção que as pessoas têm sobre sua capacidade e valor.",
        "low_text": "Apresenta a tendência a ser humilde, a não se vangloriar pelos bens e capacidades pessoais, além de pouca necessidade de receber atenção dos outros. Pode, inclusive, ter dificuldade para reconhecer suas capacidades e atributos favoráveis, mesmo que sejam evidentes.",
        "high_text": "Pode ter necessidade de receber atenção dos outros. Pode também apresentar crenças de que os demais o(a) invejam e uma predisposição para falar excessivamente sobre si, suas qualidades e suas posses.",
    },
    "E3": {
        "name": "Dinamismo",
        "factor": "EE",
        "items": [21, 26, 32, 108, 117],
        "reversed": [],
        "description": "Indica o quanto as pessoas tomam a iniciativa em situações variadas, quão facilmente julgam que colocam suas ideias em prática e seu nível de atividade.",
        "low_text": "Tende a se concentrar em um pequeno número de atividades simultâneas e não precisa estar constantemente envolvido(a) em atividades para sentirem-se bem. Além disso, pode demorar mais para colocar suas ideias em prática e tomar iniciativa para realizar certas ações.",
        "high_text": "Pode mostrar-se mais dinâmico(a), envolver-se em várias atividades simultaneamente e preferir, mesmo quando está de folga ou de férias, manter-se ocupado(a) com atividades variadas. Altos níveis de dinamismo também são associados a uma tendência à liderança e alto nível de assertividade.",
    },
    "E4": {
        "name": "Interações Sociais",
        "factor": "EE",
        "items": [8, 11, 47, 50, 52, 71, 90],
        "reversed": [],
        "description": "Descreve o desejo e necessidade por interações sociais, indicando o quanto as pessoas buscam ativamente situações que permitam tais interações, como festas, atividades em grupo, entre outras.",
        "low_text": "Tende preferir ficar sozinho(a) ou em grupos pequenos e demora mais para desenvolver novas relações sociais. Tendem também a apresentar uma necessidade reduzida de viver situações mais intensas, de frequentar lugares mais ricos em termos de estímulos e possibilidades de contatos sociais.",
        "high_text": "Tende a ser gregário(a) e esforça-se para manter contato com seus conhecidos. Pode preferir atividades em grupo e tende envolver-se rapidamente com as pessoas.",
    },
    "S1": {
        "name": "Amabilidade",
        "factor": "SS",
        "items": [2, 4, 12, 15, 20, 43, 46, 61, 92, 96, 104, 125],
        "reversed": [],
        "description": "Descreve o quão atenciosas, compreensivas e empáticas as pessoas procuram ser com as demais. Além disso, indica quão agradáveis as pessoas buscam ser com os outros, observando suas opiniões, sendo educadas com elas e se importando com suas necessidades.",
        "low_text": "Tendem a apresentar pouca disponibilidade para com os demais, sendo autocentrado(a) e indiferente às necessidades alheias. Pode demonstrar pouca preocupação em promover o bem-estar dos outros, podendo dirigir-se a elas de forma pouco cuidadosa, tratando de assuntos delicados de forma insensível, chegando a ser hostil.",
        "high_text": "Tende a ser atencioso(a) e amável com os demais, demonstrando sua preocupação com as necessidades alheias. Tende a ser proativo(a) para resolver os problemas das pessoas, bem como expor seu apreço por elas. Pode apresentar preocupação em tratar bem as demais pessoas, perguntando como estão e esforçando-se para que se sintam bem.",
    },
    "S2": {
        "name": "Pró-Sociabilidade",
        "factor": "SS",
        "items": [18, 24, 27, 63, 76, 87, 107, 109],
        "reversed": [18, 24, 27, 63, 87, 107],
        "description": "Descreve comportamentos de risco, concordância ou confronto com leis e regras sociais, moralidade, agressividade, e padrões de consumo de bebidas alcoólicas.",
        "low_text": "Tende a envolver-se em situações que podem colocá-lo(a), ou às demais pessoas, em perigo. Pode também apresenta pouca preocupação em seguir leis e regras sociais, podendo ainda apresentar uma visão que minimiza, ignora ou desqualifica a sua importância. Pode apresentar-se como manipulador(a), agindo ativamente para que as demais pessoas façam o que deseja. Pode apresentar um padrão hostil de interação com os demais, tratando-os de forma desrespeitosa ou opositora.",
        "high_text": "Tende a evitar situações de risco, bem como transgressões a leis ou regras sociais. Tende a apresentar uma postura franca com os demais, evitando pressioná-los ou induzi-los a fazerem algo que não queiram.",
    },
    "S3": {
        "name": "Confiança nas Pessoas",
        "factor": "SS",
        "items": [7, 10, 30, 39, 57, 68, 98, 119],
        "reversed": [10, 30, 39, 57, 98, 119],
        "description": "Descreve o quanto as pessoas confiam nos outros e acreditam que eles não as prejudicarão.",
        "low_text": "Tende a apresentar constante percepção de que as pessoas podem estar tentando prejudicá-lo(a) em variados contextos. Tende a ser muito ciumento(a) no que diz respeito às relações amorosas e a apresentar uma grande dificuldade em desenvolver intimidade com outros.",
        "high_text": "Pode apresentar uma postura ingênua com os demais, chegando a colocar-se em situações nas quais facilmente pode ser prejudicado(a) ou enganado(a) por pessoas mal intencionadas e manipuladoras.",
    },
    "R1": {
        "name": "Competência",
        "factor": "RR",
        "items": [28, 41, 58, 64, 67, 72, 83, 85, 91, 122],
        "reversed": [],
        "description": "Indica o quão ativamente as pessoas buscam atingir seus objetivos, bem como a predisposição para fazer sacrifícios pessoais para tanto. Também envolve a percepção que as pessoas apresentam sobre si mesmas em relação a sua capacidade para realizar ações consideradas difíceis e importantes.",
        "low_text": "Pode apresentar pouca disposição para atingir objetivos. Tende a facilmente desistir frente a obstáculos ou necessidade de fazer sacrifícios. Também tende a apresentar uma percepção desfavorável sobre sua capacidade. Pode evitar atividades complexas e desafiantes e que não possuem objetivos bem definidos.",
        "high_text": "Tende a acreditar no seu potencial para realizar várias tarefas ao mesmo tempo, a gostar de atividades complexas e desafiadoras e a possuir clareza sobre seus objetivos de vida.",
    },
    "R2": {
        "name": "Ponderação/Prudência",
        "factor": "RR",
        "items": [9, 19, 45, 101],
        "reversed": [19],
        "description": "Descrevem situações que envolvem o cuidado com a forma para expressar opiniões ou defender interesses, bem como a avaliação das possíveis consequências de ações.",
        "low_text": "Tende a falar sem pensar, a agir antes de fazer algum planejamento e a serem impulsivas. A impulsividade, nesse caso, não se relaciona necessariamente a baixa tolerância à frustração ou uma reação emocional negativa intensificada, mas sim, à falta de planejamento e organização de modo geral.",
        "high_text": "Tende a ser mais ponderado(a) quanto ao que diz e faz, tentando controlar sua impulsividade ao resolver problemas.",
    },
    "R3": {
        "name": "Empenho/Comprometimento",
        "factor": "RR",
        "items": [34, 54, 80, 103, 112, 114, 116],
        "reversed": [],
        "description": "Descrevem o quão detalhistas são as pessoas na realização de trabalhos e seu nível de exigência pessoal com a qualidade das tarefas realizadas.",
        "low_text": "Tende a ser pouco comprometido(a) com tarefas e compromissos e usualmente é descuidado(a) com a forma que realiza e conclui tarefas. Tendem também a colocar pouca energia nas atividades em que se envolve e pode, com alguma frequência, fazê-las de tal forma que a qualidade de seu trabalho seja insuficiente ou prejudicada.",
        "high_text": "Tende a dedicar-se bastante às suas atividades profissionais/acadêmicas. Tende a gostar de obter reconhecimento por seu esforço e usualmente é perfeccionista. Também tende a planejar detalhadamente os passos para a realização de alguma atividade e pode ainda ter necessidade de realizar revisões cuidadosas dos trabalhos antes de expô-los a outras pessoas.",
    },
    "A1": {
        "name": "Abertura a Ideias",
        "factor": "AA",
        "items": [23, 33, 36, 42, 53, 56, 62, 81, 88, 115],
        "reversed": [23, 33, 42, 56, 62, 81, 115],
        "description": "Descreve abertura para novos conceitos ou ideias, que podem incluir interesse por questões filosóficas, arte, fotografia, estilos musicais e diferentes expressões culturais. Também indica o padrão de uso da imaginação e da fantasia.",
        "low_text": "Tende a ser pouco curioso(a) para conhecer novos temas. Tende a ser mais conservador(a) e fiél a seus gostos artísticos e possue postura rígida quanto a conceitos.",
        "high_text": "Tende a gostar de participar de atividades que exijam imaginação ou fantasia. Pode ter interesse por ideias abstratas, discussões filosóficas, arte, e ter curiosidade sobre novas tendências musicais e por áreas afins.",
    },
    "A2": {
        "name": "Liberalismo",
        "factor": "AA",
        "items": [1, 31, 59, 69, 74, 123, 126],
        "reversed": [1],
        "description": "Descreve a forma como as pessoas lidam com diferentes valores morais e sociais e a noção que estes podem ser relativizados, que podem mudar ao longo do tempo e ser diferentes em variadas culturas e regiões.",
        "low_text": "Tende a não relativizar valores e conceitos sociais, sendo mais dogmático(a). Usualmente defende a ideia que os valores adotados não devem ser mudados com o passar do tempo.",
        "high_text": "Tende a ter uma concepção de que muitos valores sociais, éticos e legais podem ser relativizados. Pode apresenta uma compreensão de que não existem verdades absolutas ou valores inquestionáveis.",
    },
    "A3": {
        "name": "Busca por Novidades",
        "factor": "AA",
        "items": [6, 44, 49, 84, 94, 113],
        "reversed": [84],
        "description": "Descreve o quanto as pessoas gostam e buscam vivenciar novos eventos e ações, bem como a forma como lidam com a rotina.",
        "low_text": "Pode sentir-se desconfortável com a quebra de rotina, bem como possuir pouco interesse para fazer coisas que nunca fizeram antes, de conhecer lugares novos e de se colocar em situações diferentes às que vivem usualmente.",
        "high_text": "Tende buscar ativamente novidades. Pode também relatar não gostar de rotinas em contextos variados, indicando que tem pouca motivação para realizar tarefas repetitivas, ficando facilmente entediado(a) quando não pode vivenciar novos eventos.",
    },
}

NORMS = {
    "geral": {
        "N1": {"mean": 3.49, "sd": 1.23},
        "N2": {"mean": 3.68, "sd": 1.42},
        "N3": {"mean": 3.45, "sd": 1.24},
        "N4": {"mean": 2.33, "sd": 1.11},
        "NN": {"mean": 3.19, "sd": 1.0},
        "E1": {"mean": 4.28, "sd": 1.28},
        "E2": {"mean": 3.67, "sd": 1.07},
        "E3": {"mean": 4.79, "sd": 1.03},
        "E4": {"mean": 4.82, "sd": 1.11},
        "EE": {"mean": 4.34, "sd": 0.87},
        "S1": {"mean": 5.59, "sd": 0.93},
        "S2": {"mean": 5.59, "sd": 1.01},
        "S3": {"mean": 4.73, "sd": 1.01},
        "SS": {"mean": 5.3, "sd": 0.75},
        "R1": {"mean": 5.17, "sd": 0.93},
        "R2": {"mean": 4.92, "sd": 1.2},
        "R3": {"mean": 4.78, "sd": 1.07},
        "RR": {"mean": 4.96, "sd": 0.82},
        "A1": {"mean": 4.58, "sd": 1.02},
        "A2": {"mean": 4.84, "sd": 1.01},
        "A3": {"mean": 4.61, "sd": 1.03},
        "AA": {"mean": 4.68, "sd": 0.72},
    },
    "masculino": {
        "N1": {"mean": 3.25, "sd": 1.18},
        "N2": {"mean": 3.43, "sd": 1.37},
        "N3": {"mean": 3.47, "sd": 1.22},
        "N4": {"mean": 2.36, "sd": 1.14},
        "NN": {"mean": 3.06, "sd": 1.0},
        "E1": {"mean": 4.24, "sd": 1.22},
        "E2": {"mean": 3.67, "sd": 1.04},
        "E3": {"mean": 4.78, "sd": 0.99},
        "E4": {"mean": 4.74, "sd": 1.08},
        "EE": {"mean": 4.28, "sd": 0.83},
        "S1": {"mean": 5.32, "sd": 0.99},
        "S2": {"mean": 5.23, "sd": 1.1},
        "S3": {"mean": 4.57, "sd": 1.01},
        "SS": {"mean": 5.04, "sd": 0.8},
        "R1": {"mean": 5.19, "sd": 0.93},
        "R2": {"mean": 4.99, "sd": 1.17},
        "R3": {"mean": 4.65, "sd": 1.06},
        "RR": {"mean": 4.94, "sd": 0.84},
        "A1": {"mean": 4.59, "sd": 1.04},
        "A2": {"mean": 4.74, "sd": 1.05},
        "A3": {"mean": 4.61, "sd": 1.02},
        "AA": {"mean": 4.65, "sd": 0.75},
    },
    "feminino": {
        "N1": {"mean": 3.61, "sd": 1.23},
        "N2": {"mean": 3.8, "sd": 1.42},
        "N3": {"mean": 3.44, "sd": 1.25},
        "N4": {"mean": 2.32, "sd": 1.09},
        "NN": {"mean": 3.25, "sd": 0.99},
        "E1": {"mean": 4.31, "sd": 1.31},
        "E2": {"mean": 3.67, "sd": 1.08},
        "E3": {"mean": 4.79, "sd": 1.04},
        "E4": {"mean": 4.86, "sd": 1.12},
        "EE": {"mean": 4.36, "sd": 0.88},
        "S1": {"mean": 5.73, "sd": 0.87},
        "S2": {"mean": 5.77, "sd": 0.91},
        "S3": {"mean": 4.8, "sd": 1.0},
        "SS": {"mean": 5.43, "sd": 0.68},
        "R1": {"mean": 5.17, "sd": 0.92},
        "R2": {"mean": 4.89, "sd": 1.21},
        "R3": {"mean": 4.84, "sd": 1.06},
        "RR": {"mean": 4.97, "sd": 0.8},
        "A1": {"mean": 4.57, "sd": 1.01},
        "A2": {"mean": 4.88, "sd": 0.99},
        "A3": {"mean": 4.62, "sd": 1.03},
        "AA": {"mean": 4.69, "sd": 0.71},
    },
}

MIDDLE_TEXT = "Apresenta padrões comportamentais, cognitivos e emocionais comuns à maior parte da população, ou seja, tende a apresentar padrões mais adaptativos, usuais na nossa sociedade. Escores médios significam também maior flexibilidade, uma vez que em algumas situações a pessoa pode demonstrar certa característica mais intensamente e em outras, não."
