from __future__ import annotations

from docx.shared import Inches


TABLE_LAYOUT_SPECS = {
    "wisc": {
        "style": None,
        "alignment": "left",
        "shading_profile": "wisc",
        "paragraph_profile": "wisc",
        "header_no_wrap_rows": (0,),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(1.75),
            Inches(0.95),
            Inches(0.95),
            Inches(0.95),
            Inches(0.90),
            Inches(1.15),
        ],
    },
    "bpa": {
        "style": None,
        "alignment": "left",
        "shading_profile": "bpa",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.35), Inches(1.15), Inches(1.00), Inches(2.00)],
    },
    "ravlt": {
        "style": None,
        "alignment": "center",
        "vertical_align_center": True,
        "widths": [
            Inches(3.11 / 2.54),
            Inches(0.93 / 2.54), Inches(0.93 / 2.54), Inches(0.93 / 2.54), Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.93 / 2.54),
            Inches(0.82 / 2.54),
            Inches(1.36 / 2.54),
            Inches(1.36 / 2.54),
            Inches(1.2 / 2.54),
            Inches(1.2 / 2.54),
        ],
    },
    "fdt": {
        "style": None,
        "alignment": "center",
        "shading_profile": "fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [
            Inches(1295 / 1440),
            Inches(1377 / 1440),
            Inches(1411 / 1440),
            Inches(673 / 1440),
            Inches(1284 / 1440),
            Inches(3304 / 1440),
        ],
    },
    "etdah": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "first_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(3.3), Inches(1.15), Inches(0.65), Inches(0.8), Inches(1.25)],
    },
    "scared": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.3), Inches(0.9), Inches(0.9), Inches(1.1), Inches(1.1)],
    },
    "scared_parent": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.3), Inches(0.9), Inches(0.9), Inches(1.1), Inches(1.1)],
    },
    "scared_self": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.0), Inches(1.15), Inches(0.8), Inches(0.9), Inches(1.35)],
    },
    "epq": {
        "style": None,
        "alignment": "center",
        "shading_profile": "epq",
        "paragraph_profile": "center_all",
        "border_profile": "subtle_grid",
        "widths": [Inches(2.0), Inches(0.8), Inches(0.8), Inches(0.8), Inches(1.2)],
    },
    "srs2": {
        "style": None,
        "alignment": "center",
        "shading_profile": "banded_fdt",
        "paragraph_profile": "banded_first_left",
        "header_no_wrap_rows": (0,),
        "header_no_wrap_rows_with_title": (0, 1),
        "last_col_no_wrap": True,
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(2.2), Inches(1.05), Inches(0.7), Inches(0.75), Inches(1.95)],
    },
    "scale_summary": {
        "style": None,
        "alignment": "center",
        "border_profile": "subtle_grid",
        "widths": [Inches(2.2), Inches(3.0)],
    },
    "bai_scores": {
        "style": None,
        "alignment": "center",
        "shading_profile": "bai_scores",
        "paragraph_profile": "bai_scores",
        "border_profile": "subtle_grid",
        "vertical_align_center": True,
        "widths": [Inches(3.8), Inches(1.55), Inches(1.55)],
    },
    "bfp": {
        "style": None,
        "alignment": "center",
        "shading_profile": "none",
        "paragraph_profile": "center_all",
        "border_profile": "bottom_only",
    },
    "default": {
        "style": None,
        "alignment": "center",
        "shading_profile": "default",
        "paragraph_profile": "default",
        "border_profile": "subtle_grid",
    },
}
