from .adult import ADULT_ANAMNESIS_TEMPLATE
from .adolescent import ADOLESCENT_ANAMNESIS_TEMPLATE
from .infant import INFANT_ANAMNESIS_TEMPLATE

ALL_ANAMNESIS_TEMPLATES = [
    INFANT_ANAMNESIS_TEMPLATE,
    ADOLESCENT_ANAMNESIS_TEMPLATE,
    ADULT_ANAMNESIS_TEMPLATE,
]
