ADOLESCENT_ANAMNESIS_TEMPLATE = {
    "code": "anamnesis_adolescent_v2",
    "name": "Anamnese Adolescente",
    "target_type": "adolescent",
    "version": "2.0",
    "schema_payload": {
        "title": "Anamnese Adolescente",
        "description": "Modelo clínico intermediário entre infantil e adulto, estruturado por etapas.",
        "steps": [
            {
                "id": "identificacao",
                "title": "Identificação",
                "description": "Dados do adolescente e do informante.",
                "fields": [
                    {
                        "id": "patient_name",
                        "label": "Nome",
                        "type": "text",
                        "required": True,
                    },
                    {
                        "id": "birth_date",
                        "label": "Data de nascimento",
                        "type": "date",
                        "required": True,
                    },
                    {
                        "id": "age",
                        "label": "Idade",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "gender",
                        "label": "Gênero",
                        "type": "select",
                        "required": False,
                        "options": ["Masculino", "Feminino", "Outro"],
                    },
                    {
                        "id": "school",
                        "label": "Escola",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "school_year",
                        "label": "Série/ano",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "school_shift",
                        "label": "Turno",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "city",
                        "label": "Cidade",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "state",
                        "label": "Estado",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "primary_guardian",
                        "label": "Responsável principal",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "guardian_phone",
                        "label": "Telefone",
                        "type": "phone",
                        "required": False,
                    },
                    {
                        "id": "guardian_email",
                        "label": "E-mail",
                        "type": "email",
                        "required": False,
                    },
                    {
                        "id": "submitted_by_name",
                        "label": "Quem responde esta anamnese",
                        "type": "text",
                        "required": True,
                    },
                    {
                        "id": "adolescent_participated",
                        "label": "Adolescente participou da resposta?",
                        "type": "yes_no",
                        "required": False,
                    },
                ],
            },
            {
                "id": "referral",
                "title": "Encaminhamento e Queixa",
                "description": "Descrição da demanda atual.",
                "fields": [
                    {
                        "id": "referral_source",
                        "label": "Quem encaminhou",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "evaluation_reason",
                        "label": "Motivo da avaliação",
                        "type": "textarea",
                        "required": True,
                    },
                    {
                        "id": "main_complaint",
                        "label": "Queixa principal",
                        "type": "textarea",
                        "required": True,
                    },
                    {
                        "id": "difficulty_start",
                        "label": "Início das dificuldades",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "difficulty_trend",
                        "label": "Piora/melhora",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "main_contexts",
                        "label": "Em casa, escola ou ambos?",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "current_main_concern",
                        "label": "O que mais preocupa atualmente",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "evaluation_goal",
                        "label": "Objetivo da avaliação",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "family_context",
                "title": "Contexto Familiar",
                "description": "Composição familiar e relações principais.",
                "fields": [
                    {
                        "id": "family_composition",
                        "label": "Composição familiar",
                        "type": "repeater",
                        "required": False,
                        "item_fields": [
                            {
                                "id": "name",
                                "label": "Nome",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "relationship",
                                "label": "Parentesco",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "age",
                                "label": "Idade",
                                "type": "number",
                                "required": False,
                            },
                        ],
                    },
                    {
                        "id": "lives_with",
                        "label": "Com quem mora",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "relationship_mother",
                        "label": "Relação com mãe",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "relationship_father",
                        "label": "Relação com pai",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "relationship_siblings",
                        "label": "Relação com irmãos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "important_family_changes",
                        "label": "Mudanças familiares importantes",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "frequent_conflicts",
                        "label": "Conflitos frequentes?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "support_network",
                        "label": "Rede de apoio",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "development_history",
                "title": "Desenvolvimento Pregresso Relevante",
                "description": "Marcos prévios relevantes para o caso atual.",
                "fields": [
                    {
                        "id": "pregnancy_birth_intercurrences",
                        "label": "Gestação/parto com intercorrências importantes?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "motor_delay",
                        "label": "Atraso motor?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "language_delay",
                        "label": "Atraso de linguagem?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "early_socialization_difficulties",
                        "label": "Dificuldades precoces de socialização?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "past_therapies",
                        "label": "Já fez fono/TO/psicoterapia/psicopedagogia?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "development_regression",
                        "label": "Histórico de regressão?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "development_notes",
                        "label": "Observações do desenvolvimento",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "medical_history",
                "title": "Histórico Médico e Saúde Atual",
                "description": "Acompanhamentos e condições clínicas atuais.",
                "fields": [
                    {
                        "id": "current_treatments",
                        "label": "Tratamentos médicos atuais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "medical_specialties",
                        "label": "Especialidades em acompanhamento",
                        "type": "repeater",
                        "required": False,
                        "item_fields": [
                            {
                                "id": "specialty",
                                "label": "Especialidade",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "professional",
                                "label": "Profissional",
                                "type": "text",
                                "required": False,
                            },
                            {
                                "id": "frequency",
                                "label": "Frequência",
                                "type": "text",
                                "required": False,
                            },
                        ],
                    },
                    {
                        "id": "current_medications",
                        "label": "Medicações atuais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "neurological_psychiatric_history",
                        "label": "Histórico neurológico/psiquiátrico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "hospitalizations",
                        "label": "Internações",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "relevant_exams",
                        "label": "Exames relevantes",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "health_events",
                        "label": "Dores de cabeça, sono, crises, desmaios etc.",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_diagnostic_hypotheses",
                        "label": "Suspeita diagnóstica prévia",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "medical_notes",
                        "label": "Observações clínicas",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "school_life",
                "title": "Vida Escolar Atual",
                "description": "Funcionamento escolar e acadêmico do adolescente.",
                "fields": [
                    {
                        "id": "general_school_performance",
                        "label": "Desempenho geral",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "school_subject_difficulties",
                        "label": "Matérias com maior dificuldade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "reading",
                        "label": "Leitura",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "writing",
                        "label": "Escrita",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "math",
                        "label": "Matemática",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "comprehension",
                        "label": "Compreensão de enunciados",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "organization_materials",
                        "label": "Organização de materiais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "task_delivery",
                        "label": "Entrega de tarefas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "test_preparation",
                        "label": "Estudos para prova",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "procrastination",
                        "label": "Procrastinação",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "absences",
                        "label": "Faltas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "school_support",
                        "label": "Reforço escolar",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "teacher_relationship",
                        "label": "Relação com professores",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "peer_relationship",
                        "label": "Relação com colegas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "bullying_or_isolation",
                        "label": "Bullying/isolamento?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "future_academic_plans",
                        "label": "Planos acadêmicos futuros",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "sleep_food_digital",
                "title": "Sono, Alimentação e Rotina Digital",
                "description": "Rotina biológica e hábitos digitais.",
                "fields": [
                    {
                        "id": "sleep_hours",
                        "label": "Horas de sono",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "sleep_time",
                        "label": "Horário de dormir",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "sleep_difficulty",
                        "label": "Dificuldade para dormir",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "night_awakenings",
                        "label": "Despertares",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "daytime_sleepiness",
                        "label": "Sonolência diurna",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "night_phone_use",
                        "label": "Uso de celular à noite",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_food",
                        "label": "Alimentação atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "food_pattern",
                        "label": "Seletividade / excesso / recusa",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "screen_time",
                        "label": "Tempo de tela por dia",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "social_media",
                        "label": "Redes sociais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "games",
                        "label": "Jogos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "digital_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "emotional_regulation",
                "title": "Humor, Comportamento e Regulação Emocional",
                "description": "Aspectos emocionais e comportamentais atuais.",
                "fields": [
                    {
                        "id": "anxiety",
                        "label": "Ansiedade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "irritability",
                        "label": "Irritabilidade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sadness",
                        "label": "Tristeza",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "discouragement",
                        "label": "Desânimo",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "impulsivity",
                        "label": "Impulsividade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "emotional_outbursts",
                        "label": "Explosões emocionais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "frustration_tolerance",
                        "label": "Baixa tolerância à frustração",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "self_criticism",
                        "label": "Autocrítica",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "insecurity",
                        "label": "Insegurança",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "excessive_worry",
                        "label": "Preocupação excessiva",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "mood_swings",
                        "label": "Mudanças bruscas de humor",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "emotional_notes",
                        "label": "Observações emocionais",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "social_autonomy",
                "title": "Socialização e Autonomia",
                "description": "Vida social, amizades e autonomia cotidiana.",
                "fields": [
                    {
                        "id": "has_friends",
                        "label": "Tem amigos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "friendship_quality",
                        "label": "Qualidade das amizades",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "prefers_being_alone",
                        "label": "Prefere ficar sozinho?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "group_activities",
                        "label": "Participa de atividades em grupo?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "social_difficulties",
                        "label": "Dificuldades sociais?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sensitivity_to_criticism",
                        "label": "Sensibilidade a críticas?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "social_initiative",
                        "label": "Iniciativa social",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "self_care_autonomy",
                        "label": "Autonomia em autocuidado",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "routine_organization",
                        "label": "Organização da própria rotina",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "home_responsibilities",
                        "label": "Responsabilidades em casa",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "social_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "adolescent_view",
                "title": "Percepção do Próprio Adolescente",
                "description": "Espaço de autoavaliação do adolescente.",
                "fields": [
                    {
                        "id": "self_main_difficulty",
                        "label": "Como descreve sua principal dificuldade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "self_improvement",
                        "label": "O que acha que precisa melhorar",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "self_strengths",
                        "label": "O que costuma fazer bem",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "feels_at_school",
                        "label": "Como se sente na escola",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "feels_at_home",
                        "label": "Como se sente em casa",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "deals_with_demands",
                        "label": "Como lida com cobranças",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "expectations_for_assessment",
                        "label": "O que espera da avaliação",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "adolescent_notes",
                        "label": "Observações do adolescente",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "family_history",
                "title": "Histórico Familiar",
                "description": "Histórico clínico e educacional na família.",
                "fields": [
                    {
                        "id": "family_physical_history",
                        "label": "Físico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_psychiatric_history",
                        "label": "Psiquiátrico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_neurological_history",
                        "label": "Neurológico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_adhd_history",
                        "label": "TDAH",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_asd_history",
                        "label": "TEA",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_learning_history",
                        "label": "Dificuldades de aprendizagem",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_substance_history",
                        "label": "Uso de álcool/drogas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_other_history",
                        "label": "Outros",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "routine_final",
                "title": "Rotina e Observações Finais",
                "description": "Síntese de rotina e informações complementares.",
                "fields": [
                    {
                        "id": "weekday_routine",
                        "label": "Rotina da semana",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "weekend_routine",
                        "label": "Rotina do fim de semana",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "leisure_activities",
                        "label": "Atividades de lazer",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "physical_activity",
                        "label": "Atividade física",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "extra_courses",
                        "label": "Curso extra",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "responsibilities",
                        "label": "Responsabilidades",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "time_alone",
                        "label": "Tempo sozinho",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "other_important_info",
                        "label": "Outras informações importantes",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
        ],
    },
}
