ADULT_ANAMNESIS_TEMPLATE = {
    "code": "anamnesis_adult_v2",
    "name": "Anamnese Adulta",
    "target_type": "adult",
    "version": "2.0",
    "schema_payload": {
        "title": "Anamnese Adulta",
        "description": "Anamnese web estruturada para avaliação neuropsicológica em adultos.",
        "steps": [
            {
                "id": "identificacao",
                "title": "Identificação",
                "description": "Dados básicos do paciente e do informante.",
                "fields": [
                    {
                        "id": "patient_name",
                        "label": "Nome do paciente",
                        "type": "text",
                        "required": True,
                    },
                    {
                        "id": "birth_date",
                        "label": "Data de nascimento",
                        "type": "date",
                        "required": True,
                    },
                    {
                        "id": "age",
                        "label": "Idade",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "interview_date",
                        "label": "Data da entrevista",
                        "type": "date",
                        "required": True,
                    },
                    {
                        "id": "gender",
                        "label": "Gênero",
                        "type": "select",
                        "required": False,
                        "options": ["Masculino", "Feminino", "Outro"],
                    },
                    {
                        "id": "marital_status",
                        "label": "Estado civil",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "schooling",
                        "label": "Escolaridade",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "religion",
                        "label": "Religião",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "current_job",
                        "label": "Ocupação atual",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "phone",
                        "label": "Telefone",
                        "type": "phone",
                        "required": False,
                    },
                    {
                        "id": "address",
                        "label": "Endereço completo",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "email",
                        "label": "E-mail",
                        "type": "email",
                        "required": False,
                    },
                    {
                        "id": "emergency_contact",
                        "label": "Contato de emergência",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "document_id",
                        "label": "CPF/RG",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "informant_type",
                        "label": "Informante",
                        "type": "radio",
                        "required": True,
                        "options": [
                            {"label": "Próprio paciente", "value": "self"},
                            {"label": "Outra pessoa", "value": "other"},
                        ],
                    },
                    {
                        "id": "submitted_by_name",
                        "label": "Se outra pessoa, quem",
                        "type": "text",
                        "required": False,
                        "conditional": {"field": "informant_type", "equals": "other"},
                    },
                    {
                        "id": "submitted_by_relation",
                        "label": "Relação com o paciente",
                        "type": "text",
                        "required": False,
                        "conditional": {"field": "informant_type", "equals": "other"},
                    },
                ],
            },
            {
                "id": "complaint",
                "title": "Queixa e Demanda",
                "description": "Queixa principal e motivação para a avaliação.",
                "fields": [
                    {
                        "id": "referral_source",
                        "label": "Quem solicitou a avaliação",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "reason_for_assessment",
                        "label": "Motivo da procura",
                        "type": "textarea",
                        "required": True,
                    },
                    {
                        "id": "main_complaint",
                        "label": "Queixa principal",
                        "type": "textarea",
                        "required": True,
                    },
                    {
                        "id": "difficulty_start",
                        "label": "Início das dificuldades",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "difficulty_evolution",
                        "label": "Evolução",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_impact",
                        "label": "Impacto atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "occurrence_contexts",
                        "label": "Contextos em que ocorre",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "evaluation_goal",
                        "label": "Objetivo da avaliação",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "family_support",
                "title": "Núcleo Familiar e Rede de Apoio",
                "description": "Quem compõe a rede de convivência e apoio atual.",
                "fields": [
                    {
                        "id": "current_residence",
                        "label": "Com quem reside atualmente",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_core",
                        "label": "Núcleo familiar",
                        "type": "repeater",
                        "required": False,
                        "item_fields": [
                            {
                                "id": "name",
                                "label": "Nome",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "relationship",
                                "label": "Parentesco",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "gender",
                                "label": "Gênero",
                                "type": "text",
                                "required": False,
                            },
                            {
                                "id": "age",
                                "label": "Idade",
                                "type": "number",
                                "required": False,
                            },
                            {
                                "id": "profession",
                                "label": "Profissão",
                                "type": "text",
                                "required": False,
                            },
                            {
                                "id": "schooling",
                                "label": "Escolaridade",
                                "type": "text",
                                "required": False,
                            },
                        ],
                    },
                    {
                        "id": "family_relationships",
                        "label": "Relação com familiares próximos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "support_network",
                        "label": "Rede de apoio",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "has_children",
                        "label": "Filhos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "children_count",
                        "label": "Quantos",
                        "type": "number",
                        "required": False,
                        "conditional": {"field": "has_children", "equals": True},
                    },
                    {
                        "id": "family_notes",
                        "label": "Observações familiares",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "clinical_history",
                "title": "Histórico Clínico Geral",
                "description": "Saúde física e mental, tratamentos e acompanhamentos.",
                "fields": [
                    {
                        "id": "current_physical_symptoms",
                        "label": "Sintomas físicos atuais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_medical_treatment",
                        "label": "Tratamento médico atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "medical_specialties",
                        "label": "Especialidades em acompanhamento",
                        "type": "repeater",
                        "required": False,
                        "item_fields": [
                            {
                                "id": "specialty",
                                "label": "Especialidade",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "place",
                                "label": "Local de tratamento",
                                "type": "text",
                                "required": False,
                            },
                            {
                                "id": "professional",
                                "label": "Profissional",
                                "type": "text",
                                "required": False,
                            },
                        ],
                    },
                    {
                        "id": "uses_medication",
                        "label": "Uso de medicação",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "medication_details",
                        "label": "Nome e dosagem",
                        "type": "textarea",
                        "required": False,
                        "conditional": {"field": "uses_medication", "equals": True},
                    },
                    {
                        "id": "hospitalizations",
                        "label": "Internação psiquiátrica/clínica de repouso",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "hospitalization_reason",
                        "label": "Motivo da internação",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_psychotherapy",
                        "label": "Psicoterapia prévia",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_psych_assessment",
                        "label": "Avaliação psicológica prévia",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_diagnostic_hypothesis",
                        "label": "Suspeita diagnóstica",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "clinical_notes",
                        "label": "Observações clínicas",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "development_history",
                "title": "Desenvolvimento e Histórico Pregresso",
                "description": "Histórico de desenvolvimento e dificuldades pregressas.",
                "fields": [
                    {
                        "id": "development_delays",
                        "label": "Atraso motor, linguístico ou social?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "old_school_difficulties",
                        "label": "Dificuldades escolares antigas?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "literacy_history",
                        "label": "Como foi a alfabetização",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "repetition_history",
                        "label": "Repetência",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "learning_difficulties",
                        "label": "Dificuldades de aprendizagem",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "childhood_attention",
                        "label": "Atenção na infância/adolescência",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_followup",
                        "label": "Acompanhamento anterior",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "development_notes",
                        "label": "Observações do desenvolvimento",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "education_work",
                "title": "Escolaridade e Vida Ocupacional",
                "description": "Trajetória acadêmica e funcionamento ocupacional atual.",
                "fields": [
                    {
                        "id": "current_schooling",
                        "label": "Escolaridade atual",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "extra_courses",
                        "label": "Cursos técnicos/superior/pós",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "school_trajectory",
                        "label": "Trajetória escolar",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "academic_difficulties",
                        "label": "Dificuldades acadêmicas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_work",
                        "label": "Trabalho atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "profession",
                        "label": "Profissão",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "work_routine",
                        "label": "Rotina de trabalho",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "work_difficulties",
                        "label": "Dificuldades no trabalho",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "forgetfulness",
                        "label": "Esquecimentos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "organization_productivity",
                        "label": "Organização e produtividade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "functional_impact",
                        "label": "Impacto funcional",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "occupational_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "sleep_food",
                "title": "Sono e Alimentação",
                "description": "Padrões atuais de sono e alimentação.",
                "fields": [
                    {
                        "id": "sleep_pattern",
                        "label": "Como é o sono",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sleep_hours",
                        "label": "Horas por noite",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "sleeps_well",
                        "label": "Dorme bem?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "nightmares",
                        "label": "Pesadelos",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "sleep_difficulty",
                        "label": "Dificuldade para iniciar/manter",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sleep_routine",
                        "label": "Rotina para adormecer",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_food_pattern",
                        "label": "Alimentação atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "food_issue",
                        "label": "Come mal/restrita/em excesso",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "weight_issue",
                        "label": "Problema de peso",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "food_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "routine_functionality",
                "title": "Rotina Atual e Funcionalidade",
                "description": "Funcionamento cotidiano e autonomia prática.",
                "fields": [
                    {
                        "id": "weekday_routine",
                        "label": "Rotina da semana",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "weekend_routine",
                        "label": "Rotina do fim de semana",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "physical_exercises",
                        "label": "Exercícios",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "domestic_tasks",
                        "label": "Tarefas domésticas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "appointments_management",
                        "label": "Manejo de compromissos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "financial_management",
                        "label": "Organização financeira básica",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "autonomy",
                        "label": "Autonomia",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "agenda_lists",
                        "label": "Uso de agenda/listas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "daily_memory_attention",
                        "label": "Dificuldades de memória/atenção no dia a dia",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "functional_notes",
                        "label": "Observações funcionais",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "family_history",
                "title": "Histórico Familiar",
                "description": "Antecedentes relevantes na família.",
                "fields": [
                    {
                        "id": "family_physical_history",
                        "label": "Doença física",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_psychiatric_history",
                        "label": "Psiquiátrica",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_neurological_history",
                        "label": "Neurológica",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_learning_history",
                        "label": "Dificuldades de aprendizagem",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_attention_history",
                        "label": "Dificuldades de atenção",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_substance_use",
                        "label": "Uso de drogas/álcool na família",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_relationship_degree",
                        "label": "Parentesco",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "emotional_social",
                "title": "Aspectos Emocionais e Sociais",
                "description": "Funcionamento emocional e vida social atual.",
                "fields": [
                    {
                        "id": "current_mood",
                        "label": "Humor atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "anxiety",
                        "label": "Ansiedade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "irritability",
                        "label": "Irritabilidade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sadness",
                        "label": "Tristeza",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "stress",
                        "label": "Estresse",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "social_life",
                        "label": "Vida social",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "marital_relationship",
                        "label": "Relacionamento conjugal",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "emotional_support",
                        "label": "Suporte emocional",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "criticism_sensitivity",
                        "label": "Sensibilidade a críticas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "self_esteem",
                        "label": "Autoestima",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "emotional_notes",
                        "label": "Observações emocionais",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "additional_info",
                "title": "Informações Adicionais",
                "description": "Espaço final para complementações relevantes.",
                "fields": [
                    {
                        "id": "other_information",
                        "label": "Outras informações que queira acrescentar",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_neuropsych_assessment",
                        "label": "Já realizou avaliação neuropsicológica?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "previous_results",
                        "label": "Resultados prévios",
                        "type": "textarea",
                        "required": False,
                        "conditional": {
                            "field": "previous_neuropsych_assessment",
                            "equals": True,
                        },
                    },
                    {
                        "id": "final_notes",
                        "label": "Observações finais",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
        ],
    },
}
