INFANT_ANAMNESIS_TEMPLATE = {
    "code": "anamnesis_child_v2",
    "name": "Anamnese Infantil",
    "target_type": "child",
    "version": "2.0",
    "schema_payload": {
        "title": "Anamnese Infantil",
        "description": "Formulário clínico estruturado para levantamento do histórico infantil.",
        "steps": [
            {
                "id": "identificacao",
                "title": "Identificação",
                "description": "Dados básicos da criança e do informante.",
                "fields": [
                    {
                        "id": "patient_name",
                        "label": "Nome do paciente",
                        "type": "text",
                        "required": True,
                    },
                    {
                        "id": "birth_date",
                        "label": "Data de nascimento",
                        "type": "date",
                        "required": True,
                    },
                    {
                        "id": "age",
                        "label": "Idade",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "interview_date",
                        "label": "Data da entrevista",
                        "type": "date",
                        "required": True,
                    },
                    {
                        "id": "gender",
                        "label": "Gênero",
                        "type": "select",
                        "required": False,
                        "options": ["Masculino", "Feminino", "Outro"],
                    },
                    {
                        "id": "school",
                        "label": "Escola",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "school_year",
                        "label": "Ano escolar",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "city",
                        "label": "Cidade",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "state",
                        "label": "Estado",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "address",
                        "label": "Endereço",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "primary_guardian",
                        "label": "Responsável principal",
                        "type": "text",
                        "required": True,
                    },
                    {
                        "id": "guardian_phone",
                        "label": "Telefone do responsável",
                        "type": "phone",
                        "required": False,
                    },
                    {
                        "id": "guardian_email",
                        "label": "E-mail do responsável",
                        "type": "email",
                        "required": False,
                    },
                    {
                        "id": "submitted_by_name",
                        "label": "Quem está respondendo",
                        "type": "text",
                        "required": True,
                    },
                    {
                        "id": "submitted_by_relation",
                        "label": "Vínculo com a criança",
                        "type": "text",
                        "required": True,
                    },
                ],
            },
            {
                "id": "family_context",
                "title": "Contexto Familiar",
                "description": "Composição e organização familiar.",
                "fields": [
                    {
                        "id": "mother_name",
                        "label": "Nome da mãe",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "mother_age",
                        "label": "Idade da mãe",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "mother_schooling",
                        "label": "Escolaridade da mãe",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "mother_occupation",
                        "label": "Ocupação da mãe",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "father_name",
                        "label": "Nome do pai",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "father_age",
                        "label": "Idade do pai",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "father_schooling",
                        "label": "Escolaridade do pai",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "father_occupation",
                        "label": "Ocupação do pai",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "parents_marital_status",
                        "label": "Situação conjugal dos pais",
                        "type": "select",
                        "required": False,
                        "options": [
                            "Casados",
                            "Separados",
                            "Divorciados",
                            "União estável",
                            "Outro",
                        ],
                    },
                    {
                        "id": "parents_separation_child_age",
                        "label": "Se separados/divorciados, idade da criança à época",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "legal_guardian",
                        "label": "Responsável legal",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "child_origin",
                        "label": "Filho biológico/adotado/outro",
                        "type": "select",
                        "required": False,
                        "options": ["Biológico", "Adotado", "Outro"],
                    },
                    {
                        "id": "adoption_age",
                        "label": "Se adotado, com que idade",
                        "type": "number",
                        "required": False,
                        "conditional": {"field": "child_origin", "equals": "Adotado"},
                    },
                    {
                        "id": "has_siblings",
                        "label": "Possui irmãos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "siblings",
                        "label": "Irmãos",
                        "type": "repeater",
                        "required": False,
                        "conditional": {"field": "has_siblings", "equals": True},
                        "item_fields": [
                            {
                                "id": "name",
                                "label": "Nome",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "age",
                                "label": "Idade",
                                "type": "number",
                                "required": False,
                            },
                            {
                                "id": "relationship",
                                "label": "Parentesco/configuração",
                                "type": "text",
                                "required": False,
                            },
                        ],
                    },
                    {
                        "id": "household_members",
                        "label": "Quem mora com a criança",
                        "type": "repeater",
                        "required": False,
                        "item_fields": [
                            {
                                "id": "name",
                                "label": "Nome",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "relationship",
                                "label": "Parentesco",
                                "type": "text",
                                "required": True,
                            },
                            {
                                "id": "age",
                                "label": "Idade",
                                "type": "number",
                                "required": False,
                            },
                        ],
                    },
                ],
            },
            {
                "id": "referral",
                "title": "Encaminhamento e Queixa",
                "description": "Motivo da avaliação e demanda principal.",
                "fields": [
                    {
                        "id": "referral_source",
                        "label": "Quem solicitou a avaliação",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "referral_reason",
                        "label": "Motivo do encaminhamento",
                        "type": "textarea",
                        "required": True,
                    },
                    {
                        "id": "main_complaint",
                        "label": "Queixa principal",
                        "type": "textarea",
                        "required": True,
                    },
                    {
                        "id": "difficulty_start",
                        "label": "Quando começou a dificuldade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "difficulty_evolution",
                        "label": "Como tem evoluído",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "contexts_more_present",
                        "label": "Em quais contextos aparece mais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "had_intervention",
                        "label": "Já houve alguma intervenção?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "intervention_details",
                        "label": "Qual intervenção?",
                        "type": "textarea",
                        "required": False,
                        "conditional": {"field": "had_intervention", "equals": True},
                    },
                    {
                        "id": "evaluation_goal",
                        "label": "Objetivo esperado com a avaliação",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "pregnancy",
                "title": "Gestação e Pré-natal",
                "description": "Informações do período gestacional.",
                "fields": [
                    {
                        "id": "pregnancy_number",
                        "label": "Número da gravidez",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "previous_abortions",
                        "label": "Houve abortos prévios?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "maternal_age_pregnancy",
                        "label": "Idade materna na gestação",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "paternal_age_pregnancy",
                        "label": "Idade paterna na gestação",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "prenatal_done",
                        "label": "Pré-natal realizado?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_physical_conditions",
                        "label": "Condições físicas da gestação",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_sleep",
                        "label": "Sono na gravidez",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_rest",
                        "label": "Tranquilidade para descansar",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_medications",
                        "label": "Uso de medicamentos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_abort_medication",
                        "label": "Medicação para prevenir aborto",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_infections",
                        "label": "Doenças infectocontagiosas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_serious_issues",
                        "label": "Doenças sérias ou acidentes",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "substance_use_pregnancy",
                        "label": "Uso de álcool/tabaco/drogas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "activities_during_pregnancy",
                        "label": "Atividades durante a gestação",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "fetal_movements",
                        "label": "Movimentos fetais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "pregnancy_notes",
                        "label": "Observações",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "birth",
                "title": "Parto e Nascimento",
                "description": "Dados do nascimento e primeiros meses.",
                "fields": [
                    {
                        "id": "gestational_weeks",
                        "label": "Semanas de gestação",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "birth_type",
                        "label": "Tipo de parto",
                        "type": "select",
                        "required": False,
                        "options": ["Normal", "Cesárea", "Fórceps", "Outro"],
                    },
                    {
                        "id": "labor_duration",
                        "label": "Tempo de trabalho de parto",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "fetal_presentation",
                        "label": "Apresentação fetal",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "anesthesia_type",
                        "label": "Tipo de anestesia",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "birth_weight",
                        "label": "Peso ao nascer",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "birth_length",
                        "label": "Comprimento",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "apgar",
                        "label": "Apgar",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "birth_complications",
                        "label": "Complicações no nascimento",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "nicu_support",
                        "label": "Necessidade de UTI/incubadora/oxigênio",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "hospital_days",
                        "label": "Quantos dias ficou no hospital",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "postpartum_depression",
                        "label": "Depressão pós-parto materna",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "first_months_feeding",
                        "label": "Alimentação nos primeiros meses",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "first_months_sleep",
                        "label": "Sono nos primeiros meses",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "motor_development",
                "title": "Desenvolvimento Motor",
                "description": "Marcos motores e coordenação.",
                "fields": [
                    {
                        "id": "sat_age",
                        "label": "Idade em que sentou",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "crawled_age",
                        "label": "Engatinhou",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "stood_age",
                        "label": "Ficou em pé",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "walked_age",
                        "label": "Andou",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "motor_comparison",
                        "label": "Diferença em relação a outras crianças",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "laterality",
                        "label": "Lateralidade",
                        "type": "select",
                        "required": False,
                        "options": ["Direita", "Esquerda", "Indefinida"],
                    },
                    {
                        "id": "confuses_sides",
                        "label": "Confunde direita/esquerda?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "activity_level",
                        "label": "Mais agitada / parecida / mais quieta",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "motor_therapy",
                        "label": "Fez terapia motora?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "sports_history",
                        "label": "Pratica/praticou esportes?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_motor_performance",
                        "label": "Desempenho motor atual",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "language_development",
                "title": "Desenvolvimento Linguístico",
                "description": "Aquisição e uso da linguagem.",
                "fields": [
                    {
                        "id": "babbling_age",
                        "label": "Idade do balbucio",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "first_word_age",
                        "label": "Primeira palavra",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "phrase_age",
                        "label": "Combinações de 2–3 palavras",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "speech_understandable",
                        "label": "Fala inteligível para estranhos",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "speech_difficulty",
                        "label": "Dificuldade de fala?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "oral_issues",
                        "label": "Outros problemas orais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "other_language_contact",
                        "label": "Contato com outro idioma",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "speech_description",
                        "label": "Como é a fala da criança",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "language_comprehension",
                        "label": "Como é a compreensão",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "verbal_memory",
                        "label": "Memória do que é dito",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "speech_therapy",
                        "label": "Fez avaliação/terapia fono?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "speech_therapy_details",
                        "label": "Motivo, idade e tempo",
                        "type": "textarea",
                        "required": False,
                        "conditional": {"field": "speech_therapy", "equals": True},
                    },
                ],
            },
            {
                "id": "autonomy_habits",
                "title": "Autonomia, Toalete e Hábitos",
                "description": "Autonomia diária e hábitos importantes.",
                "fields": [
                    {
                        "id": "toilet_training_start",
                        "label": "Idade do início do treino de toalete",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "day_diaper_end",
                        "label": "Idade de retirada da fralda diurna",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "night_diaper_end",
                        "label": "Idade de retirada da fralda noturna",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "current_nocturnal_diuresis",
                        "label": "Diurese noturna atual?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "toilet_training_difficulties",
                        "label": "Dificuldades após o treino?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "used_pacifier",
                        "label": "Usou chupeta?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "thumb_sucking",
                        "label": "Chupou dedo?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "tics",
                        "label": "Tiques?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "repetitive_behaviors",
                        "label": "Comportamentos repetitivos",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "autonomy_notes",
                        "label": "Observações de autonomia",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "socioemotional",
                "title": "Desenvolvimento Socioemocional",
                "description": "Interação social e regulação emocional.",
                "fields": [
                    {
                        "id": "liked_affection",
                        "label": "Gostava de colo/carinhos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "social_smile",
                        "label": "Sorriso social?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "eye_contact_difficulty",
                        "label": "Dificuldade de olhar no olho?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "understands_social_cues",
                        "label": "Entende gestos e dicas sociais?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "gets_along_children",
                        "label": "Se dá bem com crianças?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "gets_along_adults",
                        "label": "Se dá bem com adultos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "has_friends",
                        "label": "Tem amigos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "keeps_friends",
                        "label": "Mantém amigos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "play_preference",
                        "label": "Prefere brincar sozinho ou acompanhado?",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "frustration_difficulty",
                        "label": "Dificuldade com frustração?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "strange_env_difficulty",
                        "label": "Dificuldade em ambientes estranhos?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "behavior_characteristics",
                        "label": "Características observadas",
                        "type": "multiselect",
                        "required": False,
                        "options": [
                            "Nervosa",
                            "Agressiva",
                            "Ingênua",
                            "Impulsiva",
                            "Preocupada",
                            "Irritável",
                            "Teimosa",
                            "Carinhosa",
                            "Tímida",
                            "Desatenta",
                        ],
                    },
                    {
                        "id": "socioemotional_notes",
                        "label": "Observações socioemocionais",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "medical_history",
                "title": "Histórico Médico",
                "description": "Informações clínicas relevantes e acompanhamento de saúde.",
                "fields": [
                    {
                        "id": "vision_exam",
                        "label": "Exame de visão e resultado",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "hearing_exam",
                        "label": "Exame de audição e resultado",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "neurologist_visit",
                        "label": "Já consultou neurologista? Motivo",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "psychiatrist_visit",
                        "label": "Já consultou psiquiatra? Motivo",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "diseases_presented",
                        "label": "Doenças já apresentadas",
                        "type": "multiselect",
                        "required": False,
                        "options": [
                            "Asma",
                            "Alergia",
                            "Convulsão",
                            "Otite",
                            "Sinusite",
                            "Traumatismo",
                            "Infecção grave",
                            "Outra",
                        ],
                    },
                    {
                        "id": "other_relevant_diseases",
                        "label": "Outras doenças relevantes",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "hospitalizations",
                        "label": "Hospitalizações",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "development_regression",
                        "label": "Regressão do desenvolvimento?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "current_medical_treatment",
                        "label": "Tratamento médico atual",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "current_medications",
                        "label": "Medicações atuais",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "allergies",
                        "label": "Alergias",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "surgeries",
                        "label": "Cirurgias",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "medical_notes",
                        "label": "Observações clínicas",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "sleep_food",
                "title": "Sono e Alimentação",
                "description": "Padrões de sono e alimentação atuais.",
                "fields": [
                    {
                        "id": "current_sleep",
                        "label": "Como é o sono atualmente",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sleep_hours",
                        "label": "Horas por noite",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "sleeps_well",
                        "label": "Dorme bem?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "nightmares",
                        "label": "Pesadelos/terror noturno?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "sleep_difficulty",
                        "label": "Dificuldade para iniciar/manter?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "sleeps_alone",
                        "label": "Dorme sozinho?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "sleep_company",
                        "label": "Se não, com quem?",
                        "type": "text",
                        "required": False,
                        "conditional": {"field": "sleeps_alone", "equals": False},
                    },
                    {
                        "id": "sleep_routine",
                        "label": "Rotina para adormecer",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "feeding_pattern",
                        "label": "Alimentação adequada / restrita / em excesso",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "food_selectivity",
                        "label": "Seletividade alimentar",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "weight_issue",
                        "label": "Problema de peso?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "feeding_notes",
                        "label": "Observações sobre alimentação",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "school_history",
                "title": "Histórico Escolar",
                "description": "Trajetória escolar e dificuldades de aprendizagem.",
                "fields": [
                    {
                        "id": "school_start_age",
                        "label": "Idade de ingresso na escola",
                        "type": "number",
                        "required": False,
                    },
                    {
                        "id": "retentions",
                        "label": "Retenções",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "school_difficulties_by_year",
                        "label": "Dificuldades por ano",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "literacy_process",
                        "label": "Alfabetização",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "likes_reading",
                        "label": "Gosta de ler?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "letter_swaps_reading",
                        "label": "Troca letras ao ler?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "letter_swaps_writing",
                        "label": "Troca letras ao escrever?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "math_performance",
                        "label": "Matemática",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "teacher_reports_difficulties",
                        "label": "Professor relata dificuldades?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "school_support",
                        "label": "Reforço escolar?",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "likes_school",
                        "label": "Gosta de ir à escola?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "grades",
                        "label": "Notas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "school_difficulty_areas",
                        "label": "Dificuldades observadas",
                        "type": "multiselect",
                        "required": False,
                        "options": [
                            "Leitura",
                            "Escrita",
                            "Aritmética",
                            "Coordenação",
                            "Percepção espacial",
                        ],
                    },
                    {
                        "id": "study_time_daily",
                        "label": "Tempo de estudo diário",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "attention_difficulties",
                        "label": "Dificuldades de concentração",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "hyperactivity",
                        "label": "Hiperatividade",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "school_relationships",
                        "label": "Relacionamento com colegas/professores",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "aggressiveness",
                        "label": "Agressividade",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "conduct_issues",
                        "label": "Distúrbios de conduta",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "parents_learning_concern",
                        "label": "Pais acham que há dificuldade de aprendizagem?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "family_school_history",
                        "label": "Histórico familiar de dificuldade escolar?",
                        "type": "yes_no",
                        "required": False,
                    },
                ],
            },
            {
                "id": "routine",
                "title": "Rotina e Atividades",
                "description": "Rotina da criança e atividades habituais.",
                "fields": [
                    {
                        "id": "weekday_routine",
                        "label": "Rotina da semana",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "weekend_routine",
                        "label": "Rotina do fim de semana",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "preferred_activities",
                        "label": "Atividades preferidas",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "caregiver_home",
                        "label": "Com quem fica em casa",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "extracurricular_activities",
                        "label": "Atividades extracurriculares",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "screen_time",
                        "label": "Tempo de tela por dia",
                        "type": "text",
                        "required": False,
                    },
                    {
                        "id": "independent_tasks",
                        "label": "O que faz sozinho",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "age_responsibilities",
                        "label": "Responsabilidades compatíveis com a idade",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "routine_notes",
                        "label": "Observações de rotina",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
            {
                "id": "family_history",
                "title": "Histórico Familiar e Informações Adicionais",
                "description": "Histórico familiar e observações finais.",
                "fields": [
                    {
                        "id": "family_physical_history",
                        "label": "Histórico familiar físico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_psychiatric_history",
                        "label": "Histórico psiquiátrico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_neurological_history",
                        "label": "Histórico neurológico",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_learning_history",
                        "label": "Dificuldades de aprendizagem na família",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_attention_history",
                        "label": "Dificuldades de atenção na família",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "family_substance_use",
                        "label": "Uso de álcool/drogas na família",
                        "type": "textarea",
                        "required": False,
                    },
                    {
                        "id": "previous_neuropsych_assessment",
                        "label": "Já fez avaliação neuropsicológica?",
                        "type": "yes_no",
                        "required": False,
                    },
                    {
                        "id": "previous_assessment_details",
                        "label": "Quando, com quem e resultado",
                        "type": "textarea",
                        "required": False,
                        "conditional": {
                            "field": "previous_neuropsych_assessment",
                            "equals": True,
                        },
                    },
                    {
                        "id": "additional_relevant_info",
                        "label": "Outras informações relevantes",
                        "type": "textarea",
                        "required": False,
                    },
                ],
            },
        ],
    },
}
